# Generated by Django 2.1.1 on 2018-09-26 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_alumnos', '0003_remove_alumnos_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='nocontrol',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
